<?php

return [
    'USD' => 'USD — US Dollar ($)',
    'EUR' => 'EUR — Euro (€)',
    'GBP' => 'GBP — British Pound (£)',
    'TZS' => 'TZS — Tanzanian Shilling',
    'KES' => 'KES — Kenyan Shilling',
    'UGX' => 'UGX — Ugandan Shilling',
    'ZAR' => 'ZAR — South African Rand',
    'NGN' => 'NGN — Nigerian Naira',
    'INR' => 'INR — Indian Rupee (₹)',
    'AED' => 'AED — UAE Dirham',
    'SAR' => 'SAR — Saudi Riyal',
    'QAR' => 'QAR — Qatari Riyal',
    'EGP' => 'EGP — Egyptian Pound',
    'MAD' => 'MAD — Moroccan Dirham',
    'GHS' => 'GHS — Ghanaian Cedi',
    'XOF' => 'XOF — West African CFA Franc',
    'XAF' => 'XAF — Central African CFA Franc',
    'CNY' => 'CNY — Chinese Yuan',
    'JPY' => 'JPY — Japanese Yen',
    'AUD' => 'AUD — Australian Dollar',
    'CAD' => 'CAD — Canadian Dollar',
    'CHF' => 'CHF — Swiss Franc',
    'TRY' => 'TRY — Turkish Lira',
    'THB' => 'THB — Thai Baht',
    'SGD' => 'SGD — Singapore Dollar',
    'MYR' => 'MYR — Malaysian Ringgit',
    'PHP' => 'PHP — Philippine Peso',
    'BRL' => 'BRL — Brazilian Real',
    'MXN' => 'MXN — Mexican Peso',
];
