<?php

return [
    'wifi' => ['label' => 'Complimentary WiFi', 'icon' => 'fa fa-wifi'],
    'guests' => ['label' => 'Up to guests', 'icon' => 'fa fa-users'],
    'king_bed' => ['label' => 'King', 'icon' => 'fa fa-bed'],
    'double_bed' => ['label' => 'Double Bed', 'icon' => 'fa fa-bed'],
    'size' => ['label' => 'Square feet', 'icon' => 'fa fa-th'],
    'parking' => ['label' => 'Free parking', 'icon' => 'fa fa-car'],
    'breakfast' => ['label' => 'Free breakfast', 'icon' => 'fa fa-coffee'],
    'coffee' => ['label' => 'Coffee Machine', 'icon' => 'fa fa-coffee'],
    'ac' => ['label' => 'Air Conditioner', 'icon' => 'fa fa-snowflake-o'],
    'minibar' => ['label' => 'Mini Bar', 'icon' => 'fa fa-glass'],
    'tv' => ['label' => 'TV', 'icon' => 'fa fa-television'],
    'iron' => ['label' => 'Iron', 'icon' => 'fa fa-fire'],
    'hottub' => ['label' => 'Hot Tub', 'icon' => 'fa fa-tint'],
    'desk' => ['label' => 'Desk and Chair', 'icon' => 'fa fa-chair'],
    'closet' => ['label' => 'Closet', 'icon' => 'fa fa-archive'],
    'balcony' => ['label' => 'Balcony', 'icon' => 'fa fa-building-o'],
    'spa' => ['label' => 'Spa services', 'icon' => 'fa fa-leaf'],
    'gym' => ['label' => 'Fitness Center', 'icon' => 'fa fa-heartbeat'],
    'microwave' => ['label' => 'Microwave', 'icon' => 'fa fa-microchip'],
    'safe' => ['label' => 'Safe', 'icon' => 'fa fa-lock'],
    'speakers' => ['label' => 'Speakers', 'icon' => 'fa fa-volume-up'],
    'accessible' => ['label' => 'Wheelchair accessible', 'icon' => 'fa fa-wheelchair'],
    'pets' => ['label' => 'Pet friendly', 'icon' => 'fa fa-paw'],
    'pool' => ['label' => 'Swimming Pool', 'icon' => 'fa fa-tint'],
    'yoga' => ['label' => 'Yoga', 'icon' => 'fa fa-child'],
    'nosmoking' => ['label' => 'No Smoking', 'icon' => 'fa fa-ban'],
    'laundry' => ['label' => 'Laundry Service', 'icon' => 'fa fa-shirtsinbulk'],
    'kettle' => ['label' => 'Electric Kettle', 'icon' => 'fa fa-coffee'],
    'concierge' => ['label' => 'Concierge', 'icon' => 'fa fa-bell'],
    'bathroom' => ['label' => 'Bathroom', 'icon' => 'fa fa-bath'],
    'hairdryer' => ['label' => 'Hair Dryer', 'icon' => 'fa fa-wind'],
];
