<?php

return [
    'property_management_system' => [
        'label' => 'Property Management',
        'icon' => 'fa fa-building',
        'route' => null,
        'route_is' => null,
        'description' => 'Set up rooms, rates, and day-to-day hotel operations.',
        'getting_started' => 2,
    ],
    'channel_manager' => [
        'label' => 'Channel Manager',
        'icon' => 'fa fa-exchange',
        'route' => 'hotel.channel-manager.update-rooms',
        'route_is' => 'hotel.channel-manager.*',
        'description' => 'Connect OTAs and sync availability across booking channels.',
        'getting_started' => 4,
    ],
    'revenue_management_software' => [
        'label' => 'Revenue Management',
        'icon' => 'fa fa-line-chart',
        'route' => 'hotel.analytics.hotel-performance',
        'route_is' => 'hotel.analytics.*',
        'description' => 'Optimize pricing and forecast demand to maximize revenue.',
        'getting_started' => 5,
    ],
    'booking_engine_website' => [
        'label' => 'Booking Engine',
        'icon' => 'fa fa-globe',
        'route' => 'hotel.dashboard',
        'route_is' => null,
        'description' => 'Accept direct bookings through your hotel website.',
        'getting_started' => 3,
    ],
    'point_of_sale_system' => [
        'label' => 'Point of Sale',
        'icon' => 'fa fa-shopping-cart',
        'route' => null,
        'route_is' => null,
        'description' => 'Manage restaurant, bar, and outlet sales.',
        'getting_started' => 6,
    ],
    'groups_chain_hotels_system' => [
        'label' => 'Branches',
        'icon' => 'fa fa-sitemap',
        'route' => 'hotel.branches.index',
        'route_is' => 'hotel.branches.*',
        'description' => 'Add and manage multiple locations for your hotel group.',
        'getting_started' => 1,
    ],
    'reviews_reputation_management' => [
        'label' => 'Reviews & Reputation',
        'icon' => 'fa fa-star',
        'route' => null,
        'route_is' => null,
        'description' => 'Monitor guest reviews and manage online reputation.',
        'getting_started' => 7,
    ],
    'purchase_inventory_management' => [
        'label' => 'Purchase & Inventory',
        'icon' => 'fa fa-cubes',
        'route' => null,
        'route_is' => null,
        'description' => 'Track stock, suppliers, and purchase orders.',
        'getting_started' => 8,
    ],
    'accounting_expenses_system' => [
        'label' => 'Accounting & Expenses',
        'icon' => 'fa fa-calculator',
        'route' => 'hotel.expenses.index',
        'route_is' => 'hotel.expenses.*',
        'description' => 'Record expenses, invoices, and financial reports.',
        'getting_started' => 9,
    ],
    'housekeeping_maintenance_system' => [
        'label' => 'Housekeeping',
        'icon' => 'fa fa-bed',
        'route' => null,
        'route_is' => null,
        'description' => 'Assign room cleaning tasks and track maintenance work.',
        'getting_started' => 10,
    ],
    'hr_employee_management_system' => [
        'label' => 'HR & Employees',
        'icon' => 'fa fa-id-badge',
        'route' => 'hotel.staff.index',
        'route_is' => 'hotel.staff.*',
        'description' => 'Manage staff profiles, shifts, and payroll basics.',
        'getting_started' => 11,
    ],
    'crm_leads_management_system' => [
        'label' => 'CRM & Leads',
        'icon' => 'fa fa-address-book',
        'route' => null,
        'route_is' => null,
        'description' => 'Capture leads and follow up with guests and corporate clients.',
        'getting_started' => 12,
    ],
    'banquets_management_system' => [
        'label' => 'Banquets',
        'icon' => 'fa fa-glass',
        'route' => null,
        'route_is' => null,
        'description' => 'Plan events, banquets, and conference bookings.',
        'getting_started' => 13,
    ],
];
