<?php

return [
    [
        'slug' => 'agoda',
        'name' => 'Agoda',
        'domain' => 'agoda.com',
        'brand_color' => '#5b2dee',
        'logo' => 'agoda.svg',
    ],
    [
        'slug' => 'airbnb',
        'name' => 'Airbnb',
        'domain' => 'airbnb.com',
        'brand_color' => '#ff5a5f',
        'logo' => 'airbnb.svg',
    ],
    [
        'slug' => 'booking-com',
        'name' => 'Booking.com',
        'domain' => 'booking.com',
        'brand_color' => '#003580',
        'logo' => 'booking-com.svg',
    ],
    [
        'slug' => 'bookings-maker',
        'name' => 'Bookings Maker',
        'domain' => 'bookingsmaker.com',
        'brand_color' => '#2563eb',
        'logo' => 'bookings-maker.svg',
    ],
    [
        'slug' => 'cleartrip',
        'name' => 'Cleartrip',
        'domain' => 'cleartrip.com',
        'brand_color' => '#ff6d38',
        'logo' => 'cleartrip.svg',
    ],
    [
        'slug' => 'trip-com',
        'name' => 'Trip.com',
        'domain' => 'trip.com',
        'brand_color' => '#287dfa',
        'logo' => 'trip-com.svg',
    ],
    [
        'slug' => 'ease-my-trip',
        'name' => 'Ease My Trip',
        'domain' => 'easemytrip.com',
        'brand_color' => '#1e88e5',
        'logo' => 'ease-my-trip.svg',
    ],
    [
        'slug' => 'expedia',
        'name' => 'Expedia',
        'domain' => 'expedia.com',
        'brand_color' => '#ffc400',
        'logo' => 'expedia.svg',
    ],
    [
        'slug' => 'goibibo',
        'name' => 'Goibibo',
        'domain' => 'goibibo.com',
        'brand_color' => '#f26722',
        'logo' => 'goibibo.svg',
    ],
    [
        'slug' => 'happyeasygo',
        'name' => 'HappyEasyGo',
        'domain' => 'happyeasygo.com',
        'brand_color' => '#00a651',
        'logo' => 'happyeasygo.svg',
    ],
    [
        'slug' => 'hostelworld',
        'name' => 'HostelWorld',
        'domain' => 'hostelworld.com',
        'brand_color' => '#f25621',
        'logo' => 'hostelworld.svg',
    ],
    [
        'slug' => 'hotelbeds',
        'name' => 'HotelBeds',
        'domain' => 'hotelbeds.com',
        'brand_color' => '#003591',
        'logo' => 'hotelbeds.svg',
    ],
    [
        'slug' => 'makemytrip',
        'name' => 'MakeMyTrip',
        'domain' => 'makemytrip.com',
        'brand_color' => '#008cff',
        'logo' => 'makemytrip.svg',
    ],
    [
        'slug' => 'reconline',
        'name' => 'Reconline',
        'domain' => 'reconline.com',
        'brand_color' => '#0d9488',
        'logo' => 'reconline.svg',
    ],
    [
        'slug' => 'tiket-com',
        'name' => 'Tiket.com',
        'domain' => 'tiket.com',
        'brand_color' => '#0064d2',
        'logo' => 'tiket-com.svg',
    ],
    [
        'slug' => 'travelguru',
        'name' => 'Travelguru',
        'domain' => 'travelguru.com',
        'brand_color' => '#e31e24',
        'logo' => 'travelguru.svg',
    ],
    [
        'slug' => 'traveloka',
        'name' => 'Traveloka',
        'domain' => 'traveloka.com',
        'brand_color' => '#0194f3',
        'logo' => 'traveloka.svg',
    ],
    [
        'slug' => 'travolounge',
        'name' => 'Travolounge',
        'domain' => 'travolounge.com',
        'brand_color' => '#7c3aed',
        'logo' => 'travolounge.svg',
    ],
    [
        'slug' => 'vhs-hub',
        'name' => 'VHS Hub',
        'domain' => 'vhshub.com',
        'brand_color' => '#111827',
        'logo' => 'vhs-hub.svg',
    ],
    [
        'slug' => 'yatra',
        'name' => 'Yatra',
        'domain' => 'yatra.com',
        'brand_color' => '#f34f1c',
        'logo' => 'yatra.svg',
    ],
];
